agents = 10

energy_pots = 20
golds = 20

energy_pot_price = 2
map_price = 3

width = 100
height = 100

[team1]
wood = 10
wheat = 10
iron = 10

[team2]
wood = 10
wheat = 10
iron = 10

[resources]
wood = 3
wheat = 3
iron = 3
